{
  "swagger": "2.0",
  "info": {
    "description": "スマートデバイスが計測した電力を取得する機能を提供するAPI。",
    "version": "2.0.0",
    "title": "Power Meter Profile"
  },
  "basePath": "/gotapi/powerMeter",
  "consumes": [
    "application/x-www-form-urlencoded",
    "multipart/form-data"
  ],
  "paths": {
    "/": {
      "get": {
        "summary": "スマートデバイスの電源状態を取得する。",
        "description": "",
        "operationId": "powerMeterGet",
        "parameters": [
          {
            "name": "serviceId",
            "in": "query",
            "description": "サービスID。取得対象スマートデバイス",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/PowerStatusResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "powerstatus": "OFF"
              }
            }
          }
        },
        "x-type": "one-shot"
      },
      "put": {
        "summary": "スマートデバイスの電源を付ける。",
        "description": "",
        "operationId": "powerMeterPut",
        "parameters": [
          {
            "name": "serviceId",
            "in": "formData",
            "description": "サービスID。取得対象スマートデバイス",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/PowerControlResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0"
              }
            }
          }
        },
        "x-type": "one-shot"
      },
      "delete": {
        "summary": "スマートデバイスの電源を消す。",
        "description": "",
        "operationId": "powerMeterDelete",
        "parameters": [
          {
            "name": "serviceId",
            "in": "query",
            "description": "サービスID。取得対象スマートデバイス",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/PowerControlResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0"
              }
            }
          }
        },
        "x-type": "one-shot"
      }
    },
    "/instantaneousCurrent": {
      "get": {
        "summary": "スマートデバイスが計測した瞬時電流量を取得する。",
        "description": "",
        "operationId": "powerMeterInstantaneousCurrentGet",
        "parameters": [
          {
            "name": "serviceId",
            "in": "query",
            "description": "サービスID。<br>取得対象スマートデバイス",
            "required": true,
            "type": "string"
          },
          {
            "name": "unit",
            "in": "query",
            "description": "瞬時電流量単位。瞬時電流量の単位を指定。<br>例：<br>'mA'<br>'A'<br>省略時は'A'",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/InstantaneousCurrentResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "instantaneouscurrent": {
                  "rphase": 1234.5,
                  "tphase": -2345.6,
                  "unit": "mA"
                }
              }
            }
          }
        },
        "x-type": "one-shot"
      }
    },
    "/instantaneousPower": {
      "get": {
        "summary": "スマートデバイスが計測した瞬時電力量を取得する。",
        "description": "",
        "operationId": "powerMeterInstantaneousPowerGet",
        "parameters": [
          {
            "name": "serviceId",
            "in": "query",
            "description": "サービスID。<br>取得対象スマートデバイス",
            "required": true,
            "type": "string"
          },
          {
            "name": "unit",
            "in": "query",
            "description": "瞬時電力量単位。瞬時電力量の単位を指定。<br>例：<br>'W'<br>'kW'<br>省略時は'W'",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/InstantaneousPowerResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "instantaneouspower": 38.4,
                "unit": "W"
              }
            }
          }
        },
        "x-type": "one-shot"
      }
    },
    "/integratedPower": {
      "get": {
        "summary": "スマートデバイスが計測した積算電力量を取得する。",
        "description": "指定した日時から過去24時間分の計測値を24または48分割して返す。（1時間または30分ごとの値を返す。）",
        "operationId": "powerMeterIntegratedPowerGet",
        "parameters": [
          {
            "name": "serviceId",
            "in": "query",
            "description": "サービスID。<br>取得対象スマートデバイス",
            "required": true,
            "type": "string"
          },
          {
            "name": "date",
            "in": "query",
            "description": "取得日付。<br>RFC 3339 例: 2014-01-01T00:00:00+0900<br>省略時はAPI実行日時が指定される",
            "required": false,
            "type": "string",
            "format": "date-time"
          },
          {
            "name": "unit",
            "in": "query",
            "description": "積算電力量単位。積算電力量の単位を指定。<br>省略時は'Wh'",
            "required": false,
            "type": "string"
          },
          {
            "name": "count",
            "in": "query",
            "description": "積算電力量コマ数。24時間分の積算電力量を指定数で返す。<br>24: 24分割＝１時間単位（デフォルト）<br>48: 48分割＝30分単位",
            "required": false,
            "type": "integer",
            "format": "int32",
            "enum": [
              24,
              48
            ]
          },
          {
            "name": "powerFlow",
            "in": "query",
            "description": "積算電力量方向指定。取得する積算電力量の方向を指定。<br>normal : 正方向<br>reverse : 逆方向<br>省略時はnormal (正方向)",
            "required": false,
            "type": "string",
            "enum": [
              "normal",
              "reverse"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/IntegratedPowerResponse"
            },
            "examples": {
              "application/json": {
                "result": 0,
                "product": "Example System",
                "version": "1.0.0",
                "integratedpower": [
                  0,
                  1,
                  2,
                  4,
                  8,
                  16,
                  32,
                  64,
                  128,
                  256,
                  512,
                  1024,
                  2048,
                  4096,
                  2048,
                  1024,
                  512,
                  256,
                  128,
                  64,
                  32,
                  16,
                  8,
                  4
                ],
                "unit": "Wh",
                "count": 24,
                "powerFlow": "normal"
              }
            }
          }
        },
        "x-type": "one-shot"
      }
    }
  },
  "definitions": {
    "PowerStatus": {
      "type": "object",
      "required": [
        "powerstatus"
      ],
      "properties": {
        "powerstatus": {
          "type": "string",
          "description": "電源状態を示す文字列。",
          "title": "電源状態",
          "enum": [
            "ON",
            "OFF",
            "UNKNOWN"
          ]
        }
      }
    },
    "PowerStatusResponse": {
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        },
        {
          "$ref": "#/definitions/PowerStatus"
        }
      ]
    },
    "PowerControlResponse": {
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        }
      ]
    },
    "IntegratedPower": {
      "type": "object",
      "required": [
        "count",
        "integratedpower",
        "powerFlow",
        "unit"
      ],
      "properties": {
        "integratedpower": {
          "type": "array",
          "description": "24時間分の計測値を返す。<br>サイズが24または48のnumberの配列。各値は積算電力量を表す実数。単位はパラメーター設定による。時間順に格納されているため、最初の要素は24時間前のもの。<br><br>例: リクエストで date=2015-08-24T15:14:00+0900, count=24  を指定した場合、0から23までの各インデックスに対応する時間帯は下記のとおり。<br>0 : 2015-08-23T15:00 ~ 15:59<br> :<br>23 :2015-08-24T14:00 ~ 14:59",
          "title": "積算電力量",
          "items": {
            "type": "number",
            "format": "double"
          }
        },
        "unit": {
          "type": "string",
          "description": "積算電力量の単位を表す。例：'Wh' 'kWh'",
          "title": "積算電力量単位"
        },
        "count": {
          "type": "integer",
          "description": "積算電力量コマ数（24または48）",
          "title": "積算電力量コマ数"
        },
        "powerFlow": {
          "type": "string",
          "description": "積算電力量方向を表す。'normal' 'reverse'",
          "title": "積算電力量方向"
        }
      }
    },
    "IntegratedPowerResponse": {
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        },
        {
          "$ref": "#/definitions/IntegratedPower"
        }
      ]
    },
    "InstantaneousPower": {
      "type": "object",
      "required": [
        "instantaneouspower",
        "unit"
      ],
      "properties": {
        "instantaneouspower": {
          "type": "number",
          "format": "double",
          "description": "瞬時電力量を表す実数。単位はパラメータ設定による。",
          "title": "瞬時電力量"
        },
        "unit": {
          "type": "string",
          "description": "瞬時電力量の単位を表す。例：'W' 'kW'",
          "title": "瞬時電力量単位"
        }
      }
    },
    "InstantaneousPowerResponse": {
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        },
        {
          "$ref": "#/definitions/InstantaneousPower"
        }
      ]
    },
    "InstantaneousCurrent": {
      "type": "object",
      "required": [
        "instantaneouscurrent"
      ],
      "properties": {
        "instantaneouscurrent": {
          "type": "object",
          "description": "瞬時電流量を表す実数。単位はパラメータによる。",
          "title": "瞬時電流量",
          "properties": {
            "rphase": {
              "type": "number",
              "format": "double",
              "description": "R相の瞬時電流量を表す実数。",
              "title": "R相瞬時電流量"
            },
            "tphase": {
              "type": "number",
              "format": "double",
              "description": "T相の瞬時電流量を表す実数。単相の場合は省略。",
              "title": "T相瞬時電流量"
            },
            "unit": {
              "type": "string",
              "description": "瞬時電流量の単位を表す。例：'mA' 'A'",
              "title": "瞬時電流量単位"
            }
          },
          "required": [
            "rphase",
            "unit"
          ]
        }
      }
    },
    "InstantaneousCurrentResponse": {
      "allOf": [
        {
          "$ref": "#/definitions/CommonResponse"
        },
        {
          "$ref": "#/definitions/InstantaneousCurrent"
        }
      ]
    },
    "CommonResponse": {
      "type": "object",
      "required": [
        "product",
        "result",
        "version"
      ],
      "properties": {
        "result": {
          "type": "integer",
          "description": "0: 正常応答<br>0以外: 異常応答",
          "title": "処理結果"
        },
        "product": {
          "type": "string",
          "description": "DeviceConnectシステムの名前。",
          "title": "システム名"
        },
        "version": {
          "type": "string",
          "description": "DeviceConnectシステムのバージョン名。",
          "title": "システムバージョン"
        },
        "hmac": {
          "type": "string",
          "description": "レスポンスに対する署名。アプリケーション側から事前にHMACキーを共有されていた場合は必須。",
          "title": "署名"
        }
      }
    }
  }
}